name: Deploy Website qua SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Lấy code từ GitHub
        uses: actions/checkout@v3

      - name: 🧹 Dọn dẹp file thừa (.git, .github, README...)
        # Lệnh này xóa các file thừa trên máy ảo GitHub trước khi upload
        run: |
          rm -rf .git
          rm -rf .github
          rm -f README.md
          rm -f .gitignore

      - name: 🚀 Đẩy code lên cPanel qua SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: "./"
          remote_path: "/home/nyugn217/fso2602.nyugn217.site/public_html/"
          # Nên để false để an toàn, không xóa file có sẵn trên hosting
          delete_remote_files: true
