name: Deploy Website qua SFTP

on:
  push:
    branches:
      - main # Hoặc tên branch bạn đang dùng

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Lấy code từ GitHub
        uses: actions/checkout@v3

      - name: 🚀 Đẩy code lên cPanel qua SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          # '.' nghĩa là lấy toàn bộ file trong GitHub
          local_path: "./"
          # Đường dẫn tuyệt đối trên server (dựa vào FileZilla của bạn)
          remote_path: "/home/hgjcyw5/fso2602.nyugn217.site/public_html/"
          # Giữ lại các file đã có trên server, chỉ ghi đè file mới
          delete_remote_files: true
